version: 2

sources:
  - name: main
    schema: main
    tables:
      - name: weather_staging

models:
  - name: weather_predictions
    description: "a simple weather prediction model"
    columns:
      - name: city
      - name: dt
      - name: temp_C
      - name: humidity
      - name: precipmm
